import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/Navbar/NavBar";
import Footer from "./components/footer/Footer";
import { chillax, synonym } from "./fonts";

export const metadata: Metadata = {
  title: "Mak Artistry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${chillax.variable} ${synonym.variable} antialiased`}
      lang="en"
    >
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
